version: '3.0'
services:
  kafka:
    container_name: kafka
    image: apache/kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
    ports:
      - 9092:9092/tcp
  connect:
    container_name: connect
    image: apache/kafka:latest
    command: /opt/kafka/bin/connect-standalone.sh /opt/connect/connect.properties /opt/connect/connector.properties
    volumes:
      - ./connect:/opt/connect
  grafana:
    container_name: 'kafka-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.6.1}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/dalelane-kafka-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.dalelane-kafka-datasource:debug
      GF_LOG_LEVEL: info
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: dalelane-kafka-datasource
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_SECURITY_ALLOW_EMBEDDING: true
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
